name = "task-logger"
main = "worker/src/index.js"
compatibility_date = "2024-04-01"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "task-logger-db"
database_id = "b4f4f6e0-9f2c-4ab2-bcad-6976d5801524"
